// SPDX-License-Identifier: AGPL-3.0-only
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import {seed,current,saveAnswer,state} from '../lib/store';
import {validCallback,secretBytes,signature,subscribe,unsubscribe,drain,eventPayload,constantEqual} from '../lib/events';
import {mcp} from '../lib/mcp';
import {overview,updateOverview} from '../lib/status-updates';
import {withUrgentFollowUp} from '../lib/single-flight';
import {readLayout,writeLayout} from '../lib/layout-store';
import {widgetRegistry,defaultLayouts,defaultRects,validateRects,changeRect} from '../lib/layout-model';
import {enqueueQuestion,cancelQuestion} from '../lib/question-queue';
import {readUsage,writeUsage} from '../lib/usage-store';
import {pendingQuestions} from '../lib/store';
import {readPanelConfig,writePanelConfig} from '../lib/panel-config';
import {writeCalendar,readCalendar} from '../lib/calendar-store';
import {validDate,eventsForDay,eventTime,dateInZone,covered,monthDays} from '../lib/calendar';
import {dotDisplayName,setDotDisplayName} from '../lib/owner-settings';
import {hasPendingQuestion,findProject} from '../lib/presentation';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+f,'utf8'));
class Statement{args:any[]=[];constructor(readonly query:string){}bind(...args:any[]){this.args=args;return this;}async first(){return sql.prepare(this.query).get(...this.args)??null;}async all(){return {results:sql.prepare(this.query).all(...this.args)};}async run(){const r=sql.prepare(this.query).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
const db:any={prepare:(q:string)=>new Statement(q),batch:async(stmts:Statement[])=>{sql.exec('BEGIN');try{const values=[];for(const s of stmts)values.push(await s.run());sql.exec('COMMIT');return values;}catch(e){sql.exec('ROLLBACK');throw e;}}};(globalThis as any).__testDB=db;
const tests:string[]=[];function pass(s:string){tests.push(s);}
const owner='fixture-owner';await seed(db,owner);const q=(await current(db,owner))!;assert.equal(JSON.parse(q.choices).length,3);pass('First-use seed has exactly three choices');
const key=Buffer.alloc(32,7),secret='whsec_'+key.toString('base64');assert.equal(await signature(secret,'e','123','{}'),'v1,'+createHmac('sha256',key).update('e.123.{}').digest('base64'));pass('Standard Webhooks HMAC matches independent Node crypto');
for(const url of ['http://chatgpt.com/cb','https://127.0.0.1/x','https://chatgpt.com.evil.test/x','https://user@chatgpt.com/x','https://chatgpt.com:444/x','https://[::1]/x'])assert.throws(()=>validCallback(url));assert.equal(validCallback('https://connectors.api.openai.com/fixture-callback'),'https://connectors.api.openai.com/fixture-callback');assert.throws(()=>validCallback('https://connectors.api.openai.com.evil.test/fixture'));assert.throws(()=>secretBytes('whsec_YQ=='));assert.equal(constantEqual('x','xx'),false);pass('Unsafe callbacks and invalid secrets rejected');
let sent:any[]=[];globalThis.fetch=(async(url:any,init:any)=>{const body=JSON.parse(init.body);sent.push({url,init,body});assert.equal(init.redirect,'manual');if(body.type==='verification')return Response.json({challenge:body.challenge});return new Response('',{status:202});}) as typeof fetch;
const p={name:'answer.submitted',arguments:{},delivery:{mode:'webhook',url:'https://chatgpt.com/test-fixture-callback',secret}};const sub=await subscribe(db,owner,p);assert.ok(sub.id);assert.equal(sent[0].body.type,'verification');assert.equal((await subscribe(db,owner,p)).id,sub.id);assert.equal(sql.prepare('SELECT count(*) AS n FROM subscriptions').get()!.n,1);pass('Signed callback challenge verified; subscription idempotent');
const input={question_id:q.id,version:q.version,choice_id:'focus',submission_id:'fixture-submission-1'};const a=await saveAnswer(db,owner,input);assert.equal((await saveAnswer(db,owner,input)).event_id,a.event_id);assert.equal((await saveAnswer(db,owner,{...input,submission_id:'fixture-submission-2'})).event_id,a.event_id);assert.equal(sql.prepare('SELECT count(*) AS n FROM answers').get()!.n,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM deliveries').get()!.n,1);pass('Atomic answer/outbox; duplicate taps and submission retry produce one answer/event');
await assert.rejects(saveAnswer(db,owner,{...input,submission_id:'fixture-submission-3',choice_id:'quiet'}));await assert.rejects(saveAnswer(db,owner,{...input,submission_id:'fixture-submission-4',version:999}));await assert.rejects(saveAnswer(db,'other-owner',input));assert.equal((await state(db,'other-owner')).answer,null);pass('Conflicting choices, stale versions and cross-user reads/writes rejected');
assert.equal((await state(db,owner)).answer?.event_id,a.event_id);pass('Reload recovers saved answer');await drain(db,owner);assert.equal((await state(db,owner)).delivery[0].status,'received');assert.equal((await state(db,owner)).answer?.acknowledged_at,null);const event=sent.at(-1);assert.deepEqual(event.body,eventPayload(a));assert.equal(event.init.headers['webhook-id'],a.event_id);pass('Exact event shape, stable event ID, receipt distinct from acknowledgement');
const rpc=async(method:string,params:any={},auth=true)=>mcp(new Request('https://fixture.test/mcp',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{'oai-authenticated-user-id':owner}:{})},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));assert.equal((await rpc('tools/call',{name:'get_touch_status'},false)).status,401);const discovery:any=await(await rpc('server/discover',{},false)).json();assert.ok(discovery.result.capabilities.events);const tools:any=await(await rpc('tools/list',{},false)).json();assert.equal(tools.result.tools.length,16);pass('MCP discovery public and data-bearing tools require identity');
await rpc('tools/call',{name:'acknowledge_touch_answer',arguments:{event_id:a.event_id}});assert.ok((await state(db,owner)).answer?.acknowledged_at);pass('Explicit acknowledgement persisted');
const exact:any=await(await rpc('tools/call',{name:'get_touch_answer',arguments:{event_id:a.event_id}})).json();assert.equal(exact.result.structuredContent.event_id,a.event_id);assert.ok(exact.result.structuredContent.acknowledged_at);const missing:any=await(await rpc('tools/call',{name:'get_touch_answer',arguments:{event_id:'nonexistent-event'}})).json();assert.ok(missing.error);pass('Exact event lookup returns acknowledgement and cannot fall back to current answer');
await unsubscribe(db,owner,p);await unsubscribe(db,owner,p);assert.equal(sql.prepare('SELECT count(*) AS n FROM subscriptions').get()!.n,0);pass('Unsubscribe idempotent');
globalThis.fetch=(async()=>Response.json({challenge:'wrong'})) as typeof fetch;await assert.rejects(subscribe(db,owner,p));assert.equal(sql.prepare('SELECT count(*) AS n FROM subscriptions').get()!.n,0);pass('Failed challenge cannot activate subscription');
for(const redirectStatus of [302,307]){globalThis.fetch=(async()=>new Response(null,{status:redirectStatus,headers:{Location:'https://untrusted.example/redirect'}})) as typeof fetch;await assert.rejects(subscribe(db,owner,p));assert.equal(sql.prepare('SELECT count(*) AS n FROM subscriptions').get()!.n,0);}pass('302 and 307 callbacks are not followed and cannot activate subscription');
await db.prepare('UPDATE question_queue SET expires=? WHERE owner=?').bind('2000-01-01T00:00:00Z',owner).run();await assert.rejects(saveAnswer(db,owner,{...input,submission_id:'fixture-expired-1'}));pass('Expired question rejects new submission');

const retryOwner='retry-fixture-owner';await seed(db,retryOwner);globalThis.fetch=(async(_url:any,init:any)=>{const body=JSON.parse(init.body);return body.type==='verification'?Response.json({challenge:body.challenge}):new Response('Unavailable',{status:503});}) as typeof fetch;await subscribe(db,retryOwner,p);const rq=(await current(db,retryOwner))!;const ra=await saveAnswer(db,retryOwner,{question_id:rq.id,version:rq.version,choice_id:'quiet',submission_id:'retry-fixture-submission'});await drain(db,retryOwner);let rs=await state(db,retryOwner);assert.equal(rs.delivery[0].status,'pending');assert.equal(rs.delivery[0].attempts,1);assert.equal(rs.answer?.event_id,ra.event_id);await drain(db,retryOwner);rs=await state(db,retryOwner);assert.equal(rs.delivery[0].attempts,1);pass('Transient failure retains saved answer and durable outbox, with backoff');
await db.prepare('UPDATE deliveries SET next_attempt=? WHERE owner=?').bind('2000-01-01T00:00:00Z',retryOwner).run();globalThis.fetch=(async()=>new Response('Gone',{status:410})) as typeof fetch;await drain(db,retryOwner);rs=await state(db,retryOwner);assert.equal(rs.delivery[0].status,'failed');assert.equal(rs.delivery[0].attempts,2);pass('410 delivery stops retries without losing answer');
const update={summary:'Fixture verified',source_timestamp:new Date().toISOString(),expected_updated_at:null,projects:[{name:'Fixture project',update:'Test complete',source_timestamp:new Date().toISOString()}]};const ov=await updateOverview(db,owner,update);assert.equal((await updateOverview(db,owner,update))?.updated_at,ov?.updated_at);assert.equal(await overview(db,'other-owner'),null);assert.equal((await current(db,owner))?.id,q.id);await assert.rejects(updateOverview(db,owner,{...update,summary:'Stale write'}));pass('Status update idempotent, owner-scoped, conflict-safe and preserves question');
const liveQuestion={expires:new Date(Date.now()+100000).toISOString()};assert.equal(hasPendingQuestion({question:liveQuestion,answer:null}),true);assert.equal(hasPendingQuestion({question:liveQuestion,answer:{acknowledged_at:null}}),false);assert.equal(hasPendingQuestion({question:liveQuestion,answer:{acknowledged_at:new Date().toISOString()}}),false);assert.equal(hasPendingQuestion({question:{expires:'2000-01-01T00:00:00Z'},answer:null}),false);assert.equal(hasPendingQuestion({question:null,answer:null}),false);pass('Question appears only when unexpired and unanswered; saved answer hides before acknowledgement');assert.equal(findProject([{name:'System status',update:'verified'}],'System status')?.update,'verified');assert.equal(findProject([{name:'Other',update:'other'}],'Project one'),undefined);pass('Dashboard uses requested projects and honest missing-data fallbacks');
function luminance(hex:string){const c=hex.replace('#','').match(/../g)!.map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];}function contrast(a:string,b:string){const aa=luminance(a),bb=luminance(b);return (Math.max(aa,bb)+.05)/(Math.min(aa,bb)+.05);}for(const [foreground,backgrounds] of [['#686862',['#f4f3ef','#ffffff','#faf9f6','#eeede7']],['#a1a1aa',['#0a0a0b','#161619','#1b1b1f','#222226']]] as [string,string[]][]){for(const bg of backgrounds)assert.ok(contrast(foreground,bg)>=4.5,`${foreground}/${bg} contrast`);}pass('Light and dark small-text palettes meet WCAG AA contrast on all card surfaces');
await setDotDisplayName(db,owner,{dot_display_name:'assistant'});assert.equal(await dotDisplayName(db,owner),'assistant');assert.equal(await dotDisplayName(db,'other-owner'),null);await setDotDisplayName(db,'other-owner',{dot_display_name:'companion'});assert.equal(await dotDisplayName(db,owner),'assistant');assert.equal(await dotDisplayName(db,'other-owner'),'companion');pass('Dot display name is owner-scoped and independent of product branding');
assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2026-99-99'),false);const calInput={calendar_name:'Fixture calendar',timezone:'America/Chicago',range_start:'2026-01-01',range_end:'2027-01-01',source_synced_at:new Date().toISOString(),expected_synced_at:null,events:[{event_id:'all-day',title:'All-day fixture',start:'2026-03-07',end:'2026-03-09',all_day:true},{event_id:'spring',title:'Spring transition',start:'2026-03-08T01:30:00-06:00',end:'2026-03-08T03:30:00-05:00',all_day:false},{event_id:'midnight',title:'Midnight ending',start:'2026-03-08T23:00:00-05:00',end:'2026-03-09T00:00:00-05:00',all_day:false},{event_id:'fall-first',title:'Earlier repeated hour',start:'2026-11-01T01:30:00-05:00',end:'2026-11-01T01:45:00-05:00',all_day:false},{event_id:'fall-second',title:'Later repeated hour',start:'2026-11-01T01:15:00-06:00',end:'2026-11-01T01:30:00-06:00',all_day:false}]};await writeCalendar(db,owner,calInput);const cs=(await readCalendar(db,owner))!;assert.equal(await readCalendar(db,'other-owner'),null);await writeCalendar(db,owner,calInput);assert.equal(eventsForDay(cs,'2026-03-09').length,0);assert.equal(eventsForDay(cs,'2026-03-08').length,3);assert.match(eventTime(cs.events.find(e=>e.event_id==='spring')!,'2026-03-08',cs.timezone),/CST.*CDT/);assert.deepEqual(eventsForDay(cs,'2026-11-01').map(e=>e.event_id),['fall-first','fall-second']);assert.equal(dateInZone('2026-09-30T02:00:00Z','America/Chicago'),'2026-09-29');assert.equal(covered(cs,'2027-01-01'),false);assert.equal(monthDays('2026-09-30').length,35);assert.equal(monthDays('2026-08-01').length,42);await assert.rejects(writeCalendar(db,owner,{...calInput,calendar_name:'Stale overwrite'}));await assert.rejects(writeCalendar(db,owner,{...calInput,events:[{...calInput.events[0],google_url:'https://example.test/private'}]}));pass('Calendar snapshot is owner-scoped, idempotent and stale-write protected');pass('All-day exclusive ends, midnight ends, multiday coverage and DST repeated-hour ordering correct');pass('Calendar coverage and safe event-link validation correct');

const cfg={expected_version:0,reviewed_with_owner:true,modules:[{id:'project-one',title:'Project one',kind:'project',placement:'primary',enabled:true,source_type:'github',source_reference:'example/repository',mode:'agent_snapshot',snapshot_key:'Fixture project',links:[{label:'Repository',url:'https://github.com/example/repository'}]}]};const savedCfg=await writePanelConfig(db,owner,cfg);assert.equal(savedCfg.version,1);assert.equal((await writePanelConfig(db,owner,cfg)).version,1);assert.equal((await readPanelConfig(db,'other-owner')).initialized,false);await assert.rejects(writePanelConfig(db,owner,{...cfg,modules:[]}));await assert.rejects(writePanelConfig(db,owner,{...cfg,expected_version:1,reviewed_with_owner:false}));await assert.rejects(writePanelConfig(db,owner,{...cfg,expected_version:1,modules:[{...cfg.modules[0],links:[{label:'bad',url:'https://example.test/?api_key=secret'}]}]}));assert.equal((await readCalendar(db,owner))?.events.length,5);pass('Owner-reviewed module configuration is versioned, idempotent, owner-scoped and rejects credential links');

const firstQueued=await enqueueQuestion(db,owner,{request_id:'queue-fixture-one',question:'First queued fixture?',choices:['A','B','C']});const secondQueued=await enqueueQuestion(db,owner,{request_id:'queue-fixture-two',question:'Second queued fixture?',choices:['A','B','C']});assert.equal((await pendingQuestions(db,owner)).length,2);const qa=await saveAnswer(db,owner,{question_id:firstQueued.question_id,version:firstQueued.version,choice_id:'1',submission_id:'queue-answer-fixture'});assert.equal((await pendingQuestions(db,owner)).length,1);const qread:any=await(await rpc('tools/call',{name:'get_touch_answer',arguments:{event_id:qa.event_id}})).json();assert.equal(qread.result.structuredContent.is_current,true);assert.equal(qread.result.structuredContent.acknowledged_at,null);await cancelQuestion(db,owner,{question_id:secondQueued.question_id,expected_version:secondQueued.version});assert.equal((await pendingQuestions(db,owner)).length,0);assert.equal((await saveAnswer(db,owner,{question_id:firstQueued.question_id,version:firstQueued.version,choice_id:'1',submission_id:'queue-answer-fixture'})).event_id,qa.event_id);pass('Needs You supports independent pending items; answering one preserves others and exact-event validity');
const u={source:'Fixture documented runtime',fetched_at:new Date().toISOString(),expected_fetched_at:null,notes:'Only returned fixture buckets',buckets:[{id:'weekly',label:'Weekly',scope:'Fixture scope',window_minutes:10080,used_percent:37,reset_at:'2026-10-05T00:00:00Z',availability:'available'},{id:'short',label:'Short window',scope:'Not returned by fixture',window_minutes:null,used_percent:null,reset_at:null,availability:'not_returned'}]};await writeUsage(db,owner,u);assert.equal((await readUsage(db,owner))?.buckets[1].availability,'not_returned');assert.equal(await readUsage(db,'other-owner'),null);await writeUsage(db,owner,u);await assert.rejects(writeUsage(db,owner,{...u,buckets:[{...u.buckets[1],used_percent:0}]}));pass('Usage snapshots preserve absent versus unlimited semantics, owner scope and idempotency');

const layoutBefore=await readLayout(db,owner);assert.equal(layoutBefore.version,0);for(const mode of ['portrait','landscape'] as const)assert.equal(validateRects(layoutBefore.layouts[mode],layoutBefore.widgets,mode),null);const draftLayouts=structuredClone(layoutBefore.layouts);draftLayouts.portrait[0].hidden=true;const layoutSaved=await writeLayout(db,owner,{expected_version:0,expected_module_version:1,layouts:draftLayouts});assert.equal(layoutSaved.version,1);assert.equal((await readLayout(db,'other-owner')).version,0);assert.deepEqual(layoutSaved.layouts.landscape,layoutBefore.layouts.landscape);assert.ok(layoutSaved.previous_layouts);assert.equal((await writeLayout(db,owner,{expected_version:0,expected_module_version:1,layouts:draftLayouts})).version,1);const conflictDraft=structuredClone(draftLayouts);conflictDraft.portrait[0].hidden=false;await assert.rejects(writeLayout(db,owner,{expected_version:0,expected_module_version:1,layouts:conflictDraft}));const restored=await writeLayout(db,owner,{expected_version:1,expected_module_version:1,layouts:layoutSaved.previous_layouts});assert.equal(restored.version,2);assert.equal((await readCalendar(db,owner))?.events.length,5);assert.equal((await readUsage(db,owner))?.buckets[0].used_percent,37);pass('Layout save/reload, per-owner scope, conflict guards, previous restore and other-data preservation correct');
const invalid=structuredClone(restored.layouts);invalid.landscape[0].x=99;await assert.rejects(writeLayout(db,owner,{expected_version:2,expected_module_version:1,layouts:invalid}));const duplicate=structuredClone(restored.layouts);duplicate.portrait[1].id=duplicate.portrait[0].id;await assert.rejects(writeLayout(db,owner,{expected_version:2,expected_module_version:1,layouts:duplicate}));pass('Layout rejects out-of-bounds, duplicate and too-small geometry');
const demoModules=[...Array.from({length:11},(_,i)=>({id:'module-'+i,title:'Fixture module '+i,kind:'project',placement:i<2?'primary':'secondary',enabled:true,source_type:'manual',mode:'agent_snapshot',links:[]})),{id:'cal',title:'Calendar',kind:'calendar',placement:'secondary',enabled:true,source_type:'google_calendar',mode:'agent_snapshot',links:[]}];const registry=widgetRegistry({version:1,initialized:true,updated_at:null,modules:demoModules as any},[]);assert.ok(registry.some(w=>w.id==='calendar-today'));assert.ok(registry.some(w=>w.id==='calendar-week'));for(const mode of ['portrait','landscape'] as const)for(const template of ['project-focus','balanced'] as const){const rects=defaultRects(registry,mode,template);assert.equal(validateRects(rects,registry,mode),null);assert.equal(new Set(rects.map(r=>r.id)).size,registry.length);}pass('Project-first portrait/landscape templates fit up to 12 source modules with bounded paging and separate Today/Week widgets');
const flightState={busy:false,queued:false};let operations=0;let release!:()=>void;const paused=new Promise<void>(resolve=>{release=resolve;});const task=withUrgentFollowUp(flightState,async()=>{operations++;if(operations===1)await paused;});await withUrgentFollowUp(flightState,async()=>{},false);await withUrgentFollowUp(flightState,async()=>{},true);release();await task;assert.equal(operations,2);assert.equal(flightState.busy,false);pass('An answer saved during a busy drain gets one immediate follow-on without faster polling');const ur=await readUsage(db,owner);const nextTime=new Date(Date.parse(ur!.fetched_at)+1000).toISOString();await writeUsage(db,owner,{...u,expected_fetched_at:ur!.fetched_at,fetched_at:nextTime,resets_fetched_at:nextTime,resets:[{title:'Fixture reset',count:2,expires_at:'2026-10-07T00:00:00Z',status:'available',scope:'Fixture only'}]});const resetSnapshot=(await readUsage(db,owner))!;assert.equal(resetSnapshot.resets?.[0].count,2);await writeUsage(db,owner,{...u,expected_fetched_at:nextTime,fetched_at:new Date(Date.parse(nextTime)+1000).toISOString()});assert.equal((await readUsage(db,owner))?.resets_fetched_at,nextTime);pass('Optional reset availability retains its own check timestamp across older writer calls');console.log(JSON.stringify({passed:tests.length,tests},null,2));
