// SPDX-License-Identifier: AGPL-3.0-only
import type {Answer,Subscription} from './store';
import {now} from './store';
export const eventDefinition={name:'answer.submitted',description:'A choice was saved on the private touch-answer page. Ordinary preferences only, never approval for consequential actions.',delivery:['webhook'],inputSchema:{type:'object',properties:{question_id:{type:'string',description:'Optional question ID. Omit to receive answers to all your current and future questions.'}},additionalProperties:false},payloadSchema:{type:'object',properties:{event_id:{type:'string'},question_id:{type:'string'},question_version:{type:'integer'},question:{type:'string'},choice_id:{type:'string'},answer:{type:'string'},saved_at:{type:'string'}},required:['event_id','question_id','question_version','question','choice_id','answer','saved_at'],additionalProperties:false}};
export function validCallback(raw:string){const url=new URL(raw);if(url.protocol!=='https:'||!['chatgpt.com','connectors.api.openai.com'].includes(url.hostname)||url.port||url.username||url.password||url.hash)throw new Error('Callback must use an approved OpenAI HTTPS host');return url.toString();}
export function secretBytes(secret:string){if(typeof secret!=='string'||!/^whsec_[A-Za-z0-9+/]+={0,2}$/.test(secret))throw new Error('Invalid signing secret');const b=Uint8Array.from(atob(secret.slice(6)),c=>c.charCodeAt(0));if(b.length<24||b.length>64)throw new Error('Invalid signing secret length');return b;}
export async function signature(secret:string,id:string,timestamp:string,body:string){const key=await crypto.subtle.importKey('raw',secretBytes(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${id}.${timestamp}.${body}`));return 'v1,'+btoa(String.fromCharCode(...new Uint8Array(sig)));}
export function constantEqual(a:string,b:string){const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);let diff=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)diff|=(x[i]||0)^(y[i]||0);return diff===0;}
export async function signedPost(s:Pick<Subscription,'id'|'url'|'secret'|'old_secret'|'rotate_until'>,id:string,value:unknown,fetcher:typeof fetch=fetch){const body=JSON.stringify(value),timestamp=String(Math.floor(Date.now()/1000));let sign=await signature(s.secret,id,timestamp,body);if(s.old_secret&&s.rotate_until&&s.rotate_until>now())sign+=' '+await signature(s.old_secret,id,timestamp,body);console.info(JSON.stringify({diagnostic:'webhook_signed',verification:id.startsWith('verify_')}));return fetcher(validCallback(s.url),{method:'POST',redirect:'manual',signal:AbortSignal.timeout(8000),headers:{'Content-Type':'application/json','webhook-id':id,'webhook-timestamp':timestamp,'webhook-signature':sign,'X-MCP-Subscription-Id':s.id},body});}
export async function subscriptionId(owner:string,url:string,questionId:string|null){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([owner,url,eventDefinition.name,questionId])));return 'sub_'+Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');}
export function subscriptionArgs(params:any){if(params?.name!==eventDefinition.name||params?.delivery?.mode!=='webhook')throw new Error('Unsupported event or delivery');const args=params.arguments??{};if(typeof args!=='object'||Array.isArray(args)||Object.keys(args).some(x=>x!=='question_id')||(args.question_id!==undefined&&(typeof args.question_id!=='string'||!args.question_id)))throw new Error('Invalid event arguments');return {url:validCallback(params.delivery.url),questionId:args.question_id??null};}
export async function subscribe(db:D1Database,owner:string,params:any){const {url,questionId}=subscriptionArgs(params);const secret=params.delivery.secret;secretBytes(secret);if(questionId){const q=await db.prepare('SELECT id FROM questions WHERE owner=? AND id=?').bind(owner,questionId).first();if(!q)throw new Error('Question not found');}const id=await subscriptionId(owner,url,questionId);const existing=await db.prepare('SELECT * FROM subscriptions WHERE owner=? AND id=?').bind(owner,id).first<Subscription>();const challenge=crypto.randomUUID()+crypto.randomUUID();let response:Response;let verificationStage='signed_request';try{response=await signedPost({id,url,secret,old_secret:null,rotate_until:null},'verify_'+crypto.randomUUID(),{type:'verification',challenge});verificationStage='response';console.info(JSON.stringify({diagnostic:'callback_response',status:response.status,content_type:response.headers.get('content-type')}));if(!response.ok){console.error(JSON.stringify({diagnostic:'callback_verification_http',status:response.status}));throw new Error('challenge_failed');}verificationStage='parse_json';const result=await response.json() as any;verificationStage='challenge_match';console.info(JSON.stringify({diagnostic:'callback_shape',keys:result&&typeof result==='object'?Object.keys(result):[],challenge_type:typeof result?.challenge}));if(typeof result?.challenge!=='string'||!constantEqual(challenge,result.challenge))throw new Error('challenge_failed');}catch(error){console.error(JSON.stringify({diagnostic:'callback_failure',stage:verificationStage,error_type:error instanceof Error?error.name:'unknown',reason:error instanceof Error?error.message.replace(/https?:\/\/[^\s]+/g,'[URL]').replace(/whsec_[A-Za-z0-9+/=]+/g,'[SECRET]').replace(/[A-Za-z0-9_+\/=.-]{32,}/g,'[REDACTED]').slice(0,300):'unknown'}));throw new CallbackError();}
 const ttl=params.ttlMs;if(ttl!==undefined&&ttl!==null&&(!Number.isFinite(ttl)||ttl<=0))throw new Error('Invalid lifetime');const expires=new Date(Date.now()+Math.min(ttl??86400000,7*86400000)).toISOString();const rotated=existing&&existing.secret!==secret;
 await db.prepare('INSERT INTO subscriptions (id,owner,url,secret,old_secret,rotate_until,question_id,expires) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET secret=excluded.secret,old_secret=excluded.old_secret,rotate_until=excluded.rotate_until,expires=excluded.expires').bind(id,owner,url,secret,rotated?existing.secret:null,rotated?new Date(Date.now()+300000).toISOString():null,questionId,expires).run();return {id,refreshBefore:expires,cursor:null,truncated:false};}
export class CallbackError extends Error{constructor(){super('Callback verification failed');}}
export async function unsubscribe(db:D1Database,owner:string,params:any){const {url,questionId}=subscriptionArgs(params),id=await subscriptionId(owner,url,questionId);await db.batch([db.prepare('DELETE FROM subscriptions WHERE owner=? AND id=?').bind(owner,id),db.prepare("UPDATE deliveries SET status='stopped',last_error='Subscription stopped' WHERE owner=? AND subscription_id=? AND status='pending'").bind(owner,id)]);return {};}
export function eventPayload(a:Answer){return {eventId:a.event_id,name:eventDefinition.name,timestamp:a.created,data:{event_id:a.event_id,question_id:a.question_id,question_version:a.version,question:a.question,choice_id:a.choice_id,answer:a.label,saved_at:a.created},cursor:null};}
export async function drain(db:D1Database,owner:string){const pending=await db.prepare("SELECT d.id,d.event_id,d.subscription_id,d.attempts FROM deliveries d WHERE d.owner=? AND d.status='pending' AND d.next_attempt<=? AND (d.lease_until IS NULL OR d.lease_until<?) LIMIT 3").bind(owner,now(),now()).all<{id:string,event_id:string,subscription_id:string,attempts:number}>();for(const d of pending.results){const lease=new Date(Date.now()+30000).toISOString();const claim=await db.prepare("UPDATE deliveries SET lease_until=? WHERE id=? AND owner=? AND status='pending' AND (lease_until IS NULL OR lease_until<?)").bind(lease,d.id,owner,now()).run();if(!claim.meta.changes)continue;const s=await db.prepare('SELECT * FROM subscriptions WHERE id=? AND owner=? AND expires>?').bind(d.subscription_id,owner,now()).first<Subscription>();const a=await db.prepare('SELECT * FROM answers WHERE event_id=? AND owner=?').bind(d.event_id,owner).first<Answer>();if(!s||!a){await db.prepare("UPDATE deliveries SET status='stopped',last_error='Subscription expired or removed',lease_until=NULL WHERE id=? AND owner=?").bind(d.id,owner).run();continue;}let status='pending',error:string|null=null,accepted:string|null=null;try{const res=await signedPost(s,a.event_id,eventPayload(a));if(res.ok){status='received';accepted=now();}else{error=`HTTP ${res.status}`;if((res.status>=300&&res.status<400)||res.status===410||res.status===413||(res.status>=400&&res.status<500&&res.status!==429))status='failed';}}catch{error='Delivery unavailable';}const attempt=d.attempts+1;if(status==='pending'&&attempt>=8)status='failed';await db.prepare('UPDATE deliveries SET status=?,attempts=?,next_attempt=?,accepted=?,last_error=?,lease_until=NULL WHERE id=? AND owner=? AND lease_until=?').bind(status,attempt,new Date(Date.now()+Math.min(3600000,5000*2**attempt)).toISOString(),accepted,error,d.id,owner,lease).run();}return {checked:pending.results.length};}
