// SPDX-License-Identifier: AGPL-3.0-only
import type {PanelConfig,PanelModule} from './panel-config';
export type Orientation='portrait'|'landscape';
export type Widget={id:string,title:string,kind:'needs'|'today'|'week'|'usage'|'project'|'briefing'|'links',module?:PanelModule};
export type Rect={id:string,page:number,x:number,y:number,w:number,h:number,hidden?:boolean};
export type Layouts={schema_version:1,portrait:Rect[],landscape:Rect[]};
export const GRID=12,MAX_PAGES=16;
export function legacyId(name:string){let hash=2166136261;for(const c of name){hash^=c.charCodeAt(0);hash=Math.imul(hash,16777619);}return 'legacy-'+(hash>>>0).toString(16);}
export function widgetRegistry(config:PanelConfig|undefined,projects:{name:string,source_url?:string}[]):Widget[]{const modules:PanelModule[]=config?.initialized?config.modules.filter(m=>m.enabled):projects.map((p,i)=>({id:legacyId(p.name),title:p.name,kind:'project',placement:i<2?'primary':'secondary',enabled:true,source_type:'manual',mode:'agent_snapshot',snapshot_key:p.name,links:p.source_url?[{label:'Source',url:p.source_url}]:[]}));const result:Widget[]=[{id:'needs-you',title:'Needs You',kind:'needs'},{id:'usage',title:'Usage',kind:'usage'}];if(config?.initialized?modules.some(m=>m.kind==='calendar'):projects.length>0)result.push({id:'calendar-today',title:'Today',kind:'today'},{id:'calendar-week',title:'This week',kind:'week'});for(const m of modules.filter(m=>m.kind!=='calendar').sort((a,b)=>Number(a.placement==='secondary')-Number(b.placement==='secondary')))result.push({id:'module:'+m.id,title:m.title,kind:m.kind as 'project'|'briefing'|'links',module:m});return result;}
export function minimum(widget:Widget,_mode:Orientation){if(widget.kind==='week')return {w:8,h:2};if(widget.kind==='needs'||widget.kind==='today')return {w:3,h:2};if(widget.kind==='usage')return {w:3,h:2};return {w:3,h:widget.module?.placement==='primary'?3:2};}
export function overlaps(a:Rect,b:Rect){return !a.hidden&&!b.hidden&&a.page===b.page&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
export function validateRects(rects:unknown,widgets:Widget[],mode:Orientation):string|null{if(!Array.isArray(rects)||rects.length!==widgets.length)return 'Every selected widget must appear exactly once';const registry=new Map(widgets.map(w=>[w.id,w]));const used=new Set<string>();for(const rect of rects){if(!rect||typeof rect!=='object'||Object.keys(rect).some(key=>!['id','page','x','y','w','h','hidden'].includes(key)))return 'Invalid rectangle fields';const widget=registry.get(rect?.id);if(!widget||used.has(rect.id))return 'Unknown or duplicate widget';used.add(rect.id);if(!['page','x','y','w','h'].every(key=>Number.isInteger(rect[key])))return 'Use whole grid units';const min=minimum(widget,mode);if(rect.hidden!==undefined&&typeof rect.hidden!=='boolean')return 'Invalid widget visibility';if(rect.page<0||rect.page>=MAX_PAGES||rect.x<0||rect.y<0||rect.w<min.w||rect.h<min.h||rect.x+rect.w>GRID||rect.y+rect.h>GRID)return 'This widget would be too small or outside the page';}for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++)if(overlaps(rects[i],rects[j]))return 'Widgets cannot overlap';return null;}
function findSpace(rects:Rect[],size:{w:number,h:number},pageLimit=MAX_PAGES){for(let page=0;page<pageLimit;page++)for(let y=0;y<=GRID-size.h;y++)for(let x=0;x<=GRID-size.w;x++){const candidate={id:'',page,x,y,...size};if(!rects.some(r=>overlaps(r,candidate)))return {page,x,y,...size};}throw new Error('No room in the bounded layout');}
export function defaultRects(widgets:Widget[],mode:Orientation,template:'project-focus'|'balanced'='project-focus'):Rect[]{const out:Rect[]=[];const add=(id:string,rect:Omit<Rect,'id'>)=>{if(widgets.some(w=>w.id===id))out.push({id,...rect});};const primary=widgets.filter(w=>w.module?.placement==='primary'),secondary=widgets.filter(w=>w.module?.placement!=='primary'&&w.module);if(mode==='portrait'){const py=template==='balanced'?2:0,ny=template==='balanced'?0:4;if(primary[0])add(primary[0].id,{page:0,x:0,y:py,w:6,h:4});if(primary[1])add(primary[1].id,{page:0,x:6,y:py,w:6,h:4});add('needs-you',{page:0,x:0,y:ny,w:6,h:2});add('usage',{page:0,x:6,y:ny,w:6,h:2});add('calendar-today',{page:0,x:0,y:6,w:6,h:2});const briefing=secondary.find(w=>w.kind==='briefing'||w.kind==='links');if(briefing)add(briefing.id,{page:0,x:6,y:6,w:6,h:2});const other=secondary.find(w=>w.id!==briefing?.id);if(other)add(other.id,{page:0,x:0,y:8,w:12,h:2});add('calendar-week',{page:0,x:0,y:10,w:12,h:2});}else if(template==='balanced'){if(primary[0])add(primary[0].id,{page:0,x:0,y:0,w:6,h:4});if(primary[1])add(primary[1].id,{page:0,x:6,y:0,w:6,h:4});add('needs-you',{page:0,x:0,y:4,w:4,h:3});add('usage',{page:0,x:4,y:4,w:4,h:3});add('calendar-today',{page:0,x:8,y:4,w:4,h:3});if(secondary[0])add(secondary[0].id,{page:0,x:0,y:7,w:6,h:3});if(secondary[1])add(secondary[1].id,{page:0,x:6,y:7,w:6,h:3});add('calendar-week',{page:0,x:0,y:10,w:12,h:2});}else{if(primary[0])add(primary[0].id,{page:0,x:0,y:0,w:4,h:8});if(primary[1])add(primary[1].id,{page:0,x:4,y:0,w:4,h:8});add('needs-you',{page:0,x:8,y:0,w:4,h:3});add('usage',{page:0,x:8,y:3,w:4,h:3});add('calendar-today',{page:0,x:8,y:6,w:4,h:2});if(secondary[0])add(secondary[0].id,{page:0,x:0,y:8,w:6,h:2});if(secondary[1])add(secondary[1].id,{page:0,x:6,y:8,w:6,h:2});add('calendar-week',{page:0,x:0,y:10,w:12,h:2});}for(const widget of widgets){if(out.some(r=>r.id===widget.id))continue;const min=minimum(widget,mode),size={w:Math.max(mode==='portrait'?6:4,min.w),h:Math.max(3,min.h)};out.push({id:widget.id,...findSpace(out,size)});}return out;}
export function defaultLayouts(widgets:Widget[]):Layouts{return {schema_version:1,portrait:defaultRects(widgets,'portrait'),landscape:defaultRects(widgets,'landscape')};}
export function reconcileLayouts(value:Layouts|null,widgets:Widget[]):Layouts{if(!value)return defaultLayouts(widgets);const result:Layouts={schema_version:1,portrait:[],landscape:[]};for(const mode of ['portrait','landscape'] as Orientation[]){for(const rect of value[mode]??[]){const widget=widgets.find(w=>w.id===rect.id);if(!widget||result[mode].some(r=>r.id===rect.id))continue;const min=minimum(widget,mode);if(rect.w>=min.w&&rect.h>=min.h&&rect.x>=0&&rect.y>=0&&rect.x+rect.w<=GRID&&rect.y+rect.h<=GRID&&rect.page>=0&&rect.page<MAX_PAGES&&!result[mode].some(r=>overlaps(r,rect)))result[mode].push(rect);}for(const widget of widgets){if(result[mode].some(r=>r.id===widget.id))continue;const min=minimum(widget,mode);result[mode].push({id:widget.id,...findSpace(result[mode],{w:Math.max(4,min.w),h:Math.max(3,min.h)})});}}return result;}
export function changeRect(rects:Rect[],id:string,patch:Partial<Omit<Rect,'id'>>,widgets:Widget[],mode:Orientation){const current=rects.find(r=>r.id===id);if(!current)return {error:'Select a widget first',rects};const candidate={...current,...patch};let next=rects.map(r=>r.id===id?candidate:r);const collisions=rects.filter(r=>r.id!==id&&overlaps(r,candidate));if(collisions.length===1&&candidate.w===current.w&&candidate.h===current.h&&collisions[0].w===current.w&&collisions[0].h===current.h&&candidate.x===collisions[0].x&&candidate.y===collisions[0].y){const other=collisions[0];next=next.map(r=>r.id===other.id?{...r,x:current.x,y:current.y,page:current.page}:r);}const error=validateRects(next,widgets,mode);return error?{error,rects}:{error:null,rects:next};}
